version: "3.7"

services:
  frpc:
    restart: always
    image: fatedier/frpc:v0.38.0
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
      - ./frpc.ini:/app/frpc.ini:ro
    environment:
      - FRP_SERVER_ADDR=127.0.0.1
      - FRP_SERVER_PORT=9870
      - FRP_SERVER_TOKEN=@#33da@s3$A!~
      - APP_REMOTE_PORT=YOURPORT
      - APP_HOST=gitlab.idianyou.cn
      - APP_PORT=443
    # networks:
    #   - frpc
    logging:
      driver: "json-file"
      options:
        max-size: "1m"

# docker network create frpc
# networks:
#   frpc:
#     external: true